apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: project-promesa
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # IMPORTANT: Replace <AWS_ACCOUNT_ID> with your 12-digit AWS account number.
          # Example: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/promesa-frontend:latest
          image: 175200622339.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: project-promesa
  labels:
    app: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
